#------------------------------------------------------------------------------------
#  \u7F13\u5B58\u65F6\u5B9E\u4F53\u7684\u952E\u7684\u683C\u5F0F
#------------------------------------------------------------------------------------
# \u7528\u6237\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.user=entity.user.
# \u5DE5\u5177\u67DC\u6743\u9650\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.poca=entity.poca.
# \u5DE5\u5177\u67DC\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.cabinet=entity.cabinet.
# \u6587\u4EF6\u5939\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.folder=entity.folder.
# \u5DE5\u5177\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.tool=entity.tool.
# \u6536\u85CF\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.favorite=entity.favorite.
